### ISSUE TITLE
Google requestLocationUpdates suited for the foreground use cases

### ISSUE THREAD

**Issue by WilliamFB** [rekab-app/background_locator#192]
I notice that the plugin [is using requestLocationUpdates](https://github.com/rekab-app/background_locator/blob/c737ab47cb038f0a79d19cd5865b8042965b0436/android/src/main/kotlin/rekab/app/background_locator/provider/GoogleLocationProviderClient.kt#L21) from Google FusedLocationProviderClient. However the [method documentation states](https://developers.google.com/android/reference/com/google/android/gms/location/FusedLocationProviderClient#requestLocationUpdates(com.google.android.gms.location.LocationRequest,%20com.google.android.gms.location.LocationCallback,%20android.os.Looper)) that this method is suited for the foreground use cases. Isn't it a problem?

**Comment by mehdok** [comment]
Not actually, I changed it in the last commit. Previously I used [requestLocationUpdates](https://developers.google.com/android/reference/com/google/android/gms/location/FusedLocationProviderClient#public-taskvoid-requestlocationupdates-locationrequest-request,-pendingintent-callbackintent) with a `PendingIntent` and `BroadcaseReceiver` to delivering the result. But there was a problem with the newest android version (#169) which forced me to use the other method and eliminate the middle mans.

As far as I know, there isn't any problem using this method even when we are in the background, because we have a `FourgroundService`, this service is responsible for showing the notification and holing the app alive and I moved all the location logics into this service.
