### ISSUE TITLE
iOS: Conflicts with Firebas Storage

### ISSUE THREAD

**Issue by ClaudeChey** [rekab-app/background_locator#256]
Firebase Cloud Storage's UploadTask doesn't work when I do BackgroundLocator.initialize() in iOS

UploadTask.snapshotEvents doesn't fire after BackgroundLocator.initialize() call, so wait forever

https://github.com/FirebaseExtended/flutterfire/issues/5976#issuecomment-869140857

**Comment by mehdok** [comment]
Hi @ClaudeChey 
Thank you for opening an issue.

This behavior is a known issue, and sadly I have no workaround for it.

Please share if you found any solution or suggestion.

**Comment by ClaudeChey** [comment]
@mehdok 
Thank you for the reply
I haven't found an alternative yet, but I'll share it when I find it.

**Comment by mehdok** [comment]
Closing this issue because the is a similar issue like this (#158);
Please feel free to open this issue whenever you want;

**Comment by santa112358** [comment]
@mehdok 
This issue itself seems different from #158 
The issue of firestore is solved by https://github.com/firebase/flutterfire/issues/4108, but firebase storage seems not. 
I think it's better to reopen this.

Thank you.

**Comment by w3ggy** [comment]
Any news? It also conflicts with https://pub.dev/packages/flutter_uploader/versions/3.0.0-beta.4 and I haven't found any workaround solutions which I could implement manually if it is not Firebase Storage package issue but looks like it is if it was fixed in Firebase Firestorage here: https://github.com/firebase/flutterfire/issues/4108#issuecomment-734723727

The main issue is closed https://github.com/firebase/flutterfire/issues/5976
